// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.9.1

//# unitInfo: Provides: Ppx_quickcheck_runtime__
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_quickcheck_runtime = [0];
   runtime.caml_register_global
    (0, Ppx_quickcheck_runtime, "Ppx_quickcheck_runtime__");
   return;
  }
  (globalThis));

//# unitInfo: Provides: Ppx_quickcheck_runtime__Quickcheckable
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    Ppx_quickcheck_runtime_Quickch = [0];
   runtime.caml_register_global
    (0,
     Ppx_quickcheck_runtime_Quickch,
     "Ppx_quickcheck_runtime__Quickcheckable");
   return;
  }
  (globalThis));

//# unitInfo: Provides: Ppx_quickcheck_runtime
(function(globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_quickcheck_runtime = [0];
   runtime.caml_register_global
    (0, Ppx_quickcheck_runtime, "Ppx_quickcheck_runtime");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3F1aWNrY2hlY2tfcnVudGltZS5jbWEuanMiLCJzZWN0aW9ucyI6W3sib2Zmc2V0Ijp7ImxpbmUiOjcsImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3F1aWNrY2hlY2tfcnVudGltZS5jbWEuanMiLCJuYW1lcyI6WyJydW50aW1lIiwiUHB4X3F1aWNrY2hlY2tfcnVudGltZSJdLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQSx5QkFBQUMseUJBQUEiLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSJdLCJpZ25vcmVMaXN0IjpbMF19fSx7Im9mZnNldCI6eyJsaW5lIjoxOSwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJwcHhfcXVpY2tjaGVja19ydW50aW1lLmNtYS5qcyIsIm5hbWVzIjpbInJ1bnRpbWUiLCJQcHhfcXVpY2tjaGVja19ydW50aW1lX1F1aWNrY2giXSwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJtYXBwaW5ncyI6IklBQUFBLFVBQUE7QUFBQSxJQUFBQyxpQ0FBQSIsInNvdXJjZXNDb250ZW50IjpbIigqIGdlbmVyYXRlZCBjb2RlICopIl0sImlnbm9yZUxpc3QiOlswXX19LHsib2Zmc2V0Ijp7ImxpbmUiOjMyLCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6InBweF9xdWlja2NoZWNrX3J1bnRpbWUuY21hLmpzIiwibmFtZXMiOlsicnVudGltZSIsIlBweF9xdWlja2NoZWNrX3J1bnRpbWUiXSwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJtYXBwaW5ncyI6Ik9BQUFBLFVBQUEseUJBQUFDLHlCQUFBIiwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
